import "server-only";

import { DatabricksDataClient } from "@/lib/data/databricks";
import { JUSTIFICATIVAS, REGRAS } from "./source";

/**
 * Write layer for HC Zerado — the module's only writes, against the two
 * app-owned tables in `projeto_brisa_performance` (ADR 0005 and
 * [[app-crud-write-path-allowed]]: the read-only rule covers the validation
 * scripts in `scripts/`, not these). Mirrors `lib/data/indicators/write.ts`.
 *
 * Nothing here is cached, and nothing here reads through the cache. Every value
 * from the request is bound as an ordinal `?` — never interpolated — including
 * the dates, which the caller has already laundered through `safeIsoDate`.
 *
 * Conventions from the real DDL (verified with SHOW CREATE TABLE):
 *   - `justificativas_hc_zerado.id` is BIGINT GENERATED BY DEFAULT AS IDENTITY,
 *     so INSERT omits it and Delta assigns one. The business key the app
 *     addresses rows by is `(matricula, data_ocorrencia)`.
 *   - `status` defaults to 'Em Análise'; `criado_em`/`atualizado_em` default to
 *     CURRENT_TIMESTAMP(). The MERGE still sets them explicitly so an update
 *     moves `atualizado_em`.
 *   - `regras_justificativa_hc` has no defaults and no identity — its single row
 *     is `id = 1`, and the app only ever updates that row.
 */

function run(sql: string, params: unknown[]): Promise<unknown[]> {
  return new DatabricksDataClient().query(sql, params);
}

export interface JustificativaInput {
  matricula: string;
  /** `yyyy-MM-dd`, already validated by `safeIsoDate`. */
  dataOcorrencia: string;
  categoria: string;
  motivo: string;
  /** The verdict, written in the same statement — see the note below. */
  status: string;
  observacaoLider: string | null;
  /** True when the form carried a verdict, so `avaliado_em` gets a timestamp. */
  avaliado: boolean;
  /** `tb_usuarios.id` of whoever is saving — null only when the e-mail has no active row. */
  usuarioId: number | null;
}

/**
 * Insert or update one person's justification for one day, verdict included.
 *
 * **One statement, not two.** The origin posted the justification and then
 * PATCHed the evaluation, because they were two HTTP endpoints; copying that
 * shape cost a second Delta MERGE round-trip for no semantic gain — measured at
 * ~6s between the two writes on a real save. Folding the verdict into the MERGE
 * reaches the same final row in one commit.
 *
 * Re-editing still resets the verdict: when the form carries none, this writes
 * `Em Análise` with `observacao_lider`/`avaliador_id`/`avaliado_em` null. The
 * approval was given for text that has just been replaced, so keeping it would
 * leave an approved justification nobody approved.
 */
export async function upsertJustificativa(input: JustificativaInput): Promise<void> {
  const avaliado = input.avaliado ? 1 : 0;
  // `avaliado_em` has to come from the warehouse clock, so it cannot be a bound
  // value — the flag picks between CURRENT_TIMESTAMP() and NULL instead.
  const avaliadoEm = "CASE WHEN ? = 1 THEN CURRENT_TIMESTAMP() END";

  await run(
    `MERGE INTO ${JUSTIFICATIVAS} AS target
     USING (SELECT CAST(? AS INT) matricula, CAST(? AS DATE) data_ocorrencia) AS source
        ON target.matricula = source.matricula
       AND target.data_ocorrencia = source.data_ocorrencia
     WHEN MATCHED THEN UPDATE SET
       categoria = ?,
       motivo = ?,
       status = ?,
       observacao_lider = ?,
       autor_id = ?,
       avaliador_id = ?,
       avaliado_em = ${avaliadoEm},
       atualizado_em = CURRENT_TIMESTAMP()
     WHEN NOT MATCHED THEN INSERT
       (matricula, data_ocorrencia, categoria, motivo, status, observacao_lider,
        autor_id, avaliador_id, avaliado_em, criado_em, atualizado_em)
     VALUES
       (source.matricula, source.data_ocorrencia, ?, ?, ?, ?, ?, ?, ${avaliadoEm},
        CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP())`,
    [
      input.matricula,
      input.dataOcorrencia,
      // WHEN MATCHED
      input.categoria,
      input.motivo,
      input.status,
      input.observacaoLider,
      input.usuarioId,
      input.avaliado ? input.usuarioId : null,
      avaliado,
      // WHEN NOT MATCHED
      input.categoria,
      input.motivo,
      input.status,
      input.observacaoLider,
      input.usuarioId,
      input.avaliado ? input.usuarioId : null,
      avaliado,
    ],
  );
}

/**
 * Remove one person's justification for one day.
 *
 * The origin had no delete at all: a justification written for the wrong day
 * could only be overwritten, never undone, so the wrong day stayed "justified"
 * forever. Keyed by the same business key as the upsert — `id` is an identity
 * column nothing addresses.
 */
export async function deleteJustificativa(matricula: string, dataOcorrencia: string): Promise<void> {
  await run(
    `DELETE FROM ${JUSTIFICATIVAS}
      WHERE matricula = CAST(? AS INT) AND data_ocorrencia = CAST(? AS DATE)`,
    [matricula, dataOcorrencia],
  );
}

export interface RegrasInput {
  servicos: string[];
  statusVenda: string;
  agilidade: string;
}

/**
 * Update the single global rules row. An UPDATE, never an upsert: the row is
 * seeded (`id = 1`) and an app that could create it would happily create a
 * second one on a typo, leaving two definitions of "zerado".
 */
export async function updateRegras(input: RegrasInput): Promise<void> {
  await run(
    `UPDATE ${REGRAS}
        SET servicos_obrigatorios = ?,
            status_venda_obrigatorio = ?,
            agilidade_obrigatoria = ?,
            atualizado_em = CURRENT_TIMESTAMP()
      WHERE id = 1`,
    [input.servicos.join(","), input.statusVenda, input.agilidade],
  );
}
